services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/application
    working_dir: /application
    container_name: weather-php

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
    container_name: weather-nginx
    depends_on:
      - php

volumes:
  db_data:
